### ISSUE TITLE
VirtualBox guest additions non installed

### ISSUE THREAD

**Issue by depaolim** [geerlingguy/ansible-role-packer-rhel#1]
"Run VirtualBox guest additions installation." fails silently
The issue was a mismatch between versions of just installed kernel-headers and running kernel.
The vm needed a full restart
And then I was able to install VirtualBox guest additions

How can I manage a full restart inside ansible? No way, I think
Now I'm trying to split the role:
1) ansible pre-requisites (via "ansible-local" provisioning)
2) restart (via packer "shell" provisioning)
3) VirtualBox guest additions (via "ansible-local" provisioning)

Any idea? Thanks!

**Comment by geerlingguy** [comment]
I haven't had this issue with my Packer build configuration with either CentOS 6 or 7:
- https://github.com/geerlingguy/packer-centos-6
- https://github.com/geerlingguy/packer-centos-7

Are you using a different version of RHEL/CentOS or a nonstandard Packer configuration?

**Comment by depaolim** [comment]
Thanks for the answer!

I tried with:
- https://github.com/geerlingguy/packer-centos-7

and it works correctly

I close this issue

**Comment by geerlingguy** [comment]
Great! Glad you could get it working—that Packer config does some of the extra steps necessary, as the full build can't easily be done via this role alone.

**Comment by depaolim** [comment]
I write down my steps in case someone needs them

My host is ubuntu 14.04 so my default virtualbox is VirtualBox 4.3.10

Maybe I stumbled on this virtualbox bug
https://www.virtualbox.org/ticket/12879

I upgraded to the last virtualbox (currently 4.3.28):

```
wget http://download.virtualbox.org/virtualbox/4.3.28/virtualbox-4.3_4.3.28-100309~Ubuntu~raring_amd64.deb
sudo dpkg -i virtualbox-4.3_4.3.28-100309~Ubuntu~raring_amd64.deb
```

Now everything works fine
Thanks again
