### ISSUE TITLE
Potential issues with CentOS 7.5 (1804) and Virtualbox

### ISSUE THREAD

**Issue by stevenscg** [geerlingguy/ansible-role-packer-rhel#14]
I recently ran into an issue with certain packer builds stalling and failing maybe 80% of the time.

This was occurring on a packer template and ansible playbook that had largely worked quite reliably for several years. I had started to update the base image to CentOS 7.5 (1804) when I first noticed it.

I originally thought it was a packer issue and wrote about it here: https://groups.google.com/forum/#!topic/packer-tool/30Uy3u-zfUo

As noted in the mailing list posts, I tried various combinations of CentOS, Virtualbox, Packer, and Ansible. None of those changes seemed to help, nor did returning to what I believed were previously known good versions and configurations.

The last system log entries observed when this issue happened were for dhcp and NetworkManager.

What has appeared to help though is removing several tasks from this role:
* Fix slow DNS (adapted from Bento).
* Restart network service (explicitly).
* Remove RedHat interface persistence (step 1).
* Remove RedHat interface persistence (step 2).

These changes appear to result in stable runs with Vagrant 2.1.1, Virtualbox 5.2.12 on OSX, Packer 1.2.3, and Ansible 2.5.3.

Unfortunately, I don't have a repeatable test case that I can share right now. The playbook I'm using is building an "everything" development environment and runs for some time. I have a theory that a shorter run would possibly not run long enough for the dhcp retries and timeouts noted in the mailing list post to show up.

I would be interested to hear if others have any similar issues with this configuration and whether removing these tasks helps the issue.

**Comment by geerlingguy** [comment]
@stevenscg - I've been using the same config for my `geerlingguy/centos7` base box and just rebuilt it with the same versions last week, without any issues running it (I did it twice since I was testing a new build process)... not sure why those things would start failing all the sudden for you.

**Comment by stevenscg** [comment]
@geerlingguy Yeah, I haven't been able to make any sense of it either. Good to know that those versions are still working for you.

**Comment by geerlingguy** [comment]
Going to close this for now... but please let me know if you find anything more on it!
