### ISSUE TITLE
Add elfutils-libelf-devel to fix Vbox Guest Additions in CentOS 8

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-packer-rhel#21]
Add `elfutils-libelf-devel` to package list since it's not installed by default on CentOS 8 but it is apparently needed for VirtualBox Guest Additions; see https://github.com/geerlingguy/packer-centos-8/issues/4

**Comment by sulxx** [comment]
thanks!!!!!!!!
