### ISSUE TITLE
add repo for RHEL8

### ISSUE THREAD

**Issue by stefangweichinger** [geerlingguy/ansible-role-packer-rhel#23]
I currently try to deploy a RHEL 8.x VM using your role, and it seems to fail at the missing repo.
Your template only writes the repo file when version = 7 ... I assume this is the problem here.

AFAI see here:  https://www.vmware.com/support/packages.html  there is no repo for RHEL 8.x, so I have to find out how to proceed here

**Comment by geerlingguy** [comment]
I build this CentOS 8 image with this role: https://app.vagrantup.com/geerlingguy/boxes/centos8

But I don't have the licensing to build RHEL boxes, so any support would be up to you if what works for CentOS doesn't work for RHEL.

**Comment by stefangweichinger** [comment]
thanks for the reply .. I already switched to another role that works for me now ;-)
